spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1700000   # ~28분 (MySQL 타임아웃보다 짧게)
      keepalive-time: 300000  # 5분(옵션)
      leak-detection-threshold: 20000  # 20초 넘게 반납 안 하면 스택트레이스 로그

  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        hbm2ddl.auto: update
        default_batch_fetch_size: 1000

  ai:
#    retry:
#      enabled: false           # 실패 즉시 예외 던지도록
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
app:
  server-uri: ${SERVER_URI}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  auth-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: INFO     # 또는 WARN
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    # SSE 관련 Spring Security 에러 로그 숨기기
    org.springframework.security.web.access.ExceptionTranslationFilter: WARN
    org.apache.catalina.core.ContainerBase: WARN
    org.springframework.boot.web.servlet.support.ErrorPageFilter: OFF

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: akkimi_BE.aja